apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # Always means pull the latest image of nginx
  nodeSelector: # NodeSelector to specify node selection criteria
    disktype: ssd # Schedule the Pod on nodes with label 'disktype=ssd' this is node label 
    # NodeSelector is used to schedule this Pod on nodes with the label 'disktype=ssd'
    # This ensures that the Pod runs only on nodes that have SSD storage