apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo-1
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd
    # NodeSelector is used to schedule this Pod on nodes with the label 'disktype=ssd'
    # This ensures that the Pod runs only on nodes that have SSD storage